---
title: "{ mtauberjr }"
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://mtauberjr.xyz
baseurl: https://mtauberjr.xyz
google-tracking-id: ''
force-https: true
lang: en
author: Michael Tauber
description: Blog and website of Michael Tauber, blogging mainly for tech. Opinions
  expressed are mine.
keywords: tauber, michael, personal, jekyll, theme, mtauberjr
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
background-img: "/img/3.jpg"
dynamic-typing: true
shuffle: true
loop: true
loop-count: false
type-speed: 10
start-delay: 200
delete-delay: 5000
lines:
- text: Added Have I been Pwned? to pages
- text: Added Adblock iOS to Pages
- text: Added Rufus to Pages
- text: Added Delete Personal data from MS Cloud to Pages
- text: Added uBlock Origin to Pages
me-img: "/img/me.jpg"
color-browser: "#000000"
apple-status-bar-style: black
web-app-mode: true
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"
post-preview-words: 96
paginate: 5
email-share: true
fb-share: true
twitter-share: true
linkedin-share: true
reddit-share: true
google-plus-share: true
tumblr-share: true
pinterest-share: true
pocket-share: true
vkontakte-share: true
disqus-shortname: mtauberjr
syntax-highlight: true
events:
- image: "/img/ninite.png"
  date: Ninite
  description: Install Multiple Programs Quickly without Toolbars and Junk
  url: http://ninite.com
- image: "/img/Screenmaker.png"
  date: ScreenPush
  description: Bringing Animated Wallpapers to macOS by Me
  url: "/ScreenPush"
- image: "/img/adblock.jpg"
  date: Adblock iOS
  description: Best Adblocker on iOS Block more then just Safari
  url: https://www.adblockios.com/
- image: "/img/pwn.png"
  date: Have I Been Pwned?
  description: Check if you have an account that has been compromised in a data breach
  url: https://haveibeenpwned.com/
- image: "/img/rufus.png"
  date: Rufus
  description: Create bootable USB drives the easy way
  url: https://rufus.akeo.ie/
- image: "/img/clean.jpg"
  date: Delete Synced Data on 8 and 10
  description: Delete your personal settings from the cloud
  url: https://onedrive.live.com/win8personalsettingsprivacy/
- image: "/img/ublock.png"
  date: uBlock Origin
  description: Highly Recommended Chrome Extension
  url: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en
timeline-img: "/img/timeline/default.png"
email: mtauberjr@gmail.com
author_blurb: Blog From Michael Tauber
author_blurb_image: "/img/me.jpg"
social:
- title: facebook
  url: https://facebook.com/yottamike
- title: twitter
  url: https://twitter.com/mtauberjr
- title: github
  url: https://github.com/mtauberjr
- title: paypal
  url: https://PayPal.Me/mtauberjr
- title: rss
  url: "/feed.xml"
404-img: "/img/labtocat.png"
pages_list:
  Twitter: about
  Blog: latest-post
  Pages: timeline
  Contact: contact
exclude:
- LICENSE
- README.md
- CONTRIBUTING
- CONTRIBUTORS
- scripts
paginate_path: blog/page:num/
sass:
  style: compressed
gems:
- jekyll-paginate
- jemoji
